# Generated by Django 3.1.5 on 2021-01-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=20)),
                ('L_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('DOB', models.DateField()),
                ('Aadhar', models.FileField(upload_to='adhar/')),
                ('GST', models.FileField(upload_to='GST/')),
                ('PAN', models.FileField(upload_to='pan/')),
                ('Passbook', models.FileField(upload_to='Account/')),
                ('Account', models.IntegerField()),
                ('Ifsc', models.CharField(max_length=100)),
            ],
        ),
    ]
