# Generated by Django 3.1.5 on 2021-01-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='category_name',
        ),
    ]
