# Generated by Django 3.1.5 on 2021-01-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210112_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men Fashion', 'Men Fashion'), ('Women Fashion', 'Women Fashion'), ('Electronics', 'Electronics')], max_length=50),
        ),
    ]
